---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
spec:
  selector:
    app: usermanagement
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080